### ISSUE TITLE
problem with lastest update

### ISSUE THREAD

**Issue by szentigrad3** [CitiesSkylinesMods/AutoRepair#25]
since the latest update this errors happen > 

AutoRepair v0.0.0.0

[StorageManager.Load] AutoRepair.Options.xml
It looks like there's something wrong with your game install; try common fixes:
 https://steamcommunity.com/sharedfiles/filedetails/?id=467110757 

System.TypeLoadException: Could not load type 'System.Xml.Serialization.XmlRootAttribute' from assembly 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  at AutoRepair.Util.StorageManager`1[AutoRepair.Options].Load () [0x00000] in <filename unknown>:0 
  at AutoRepair.Options.get_Instance () [0x00000] in <filename unknown>:0 
  at AutoRepair.SettingsUI.Render (UIHelperBase helper, System.String scene) [0x00000] in <filename unknown>:0 
  at AutoRepair.UserMod.OnSettingsUI (UIHelperBase helper) [0x00000] in <filename unknown>:0 
   at AutoRepair.Util.Log.LogToFile(System.String message, LogLevel level, Boolean copyToGameLog)
   at AutoRepair.Util.Log.Error(System.String message, Boolean copyToGameLog)
   at AutoRepair.UserMod.OnSettingsUI(UIHelperBase helper)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at OptionsMainPanel.AddUserMods()
   at OptionsMainPanel.CreateCategories()
   at OptionsMainPanel.Awake()
   at UnityEngine.Object.Internal_CloneSingle(UnityEngine.Object )
   at UnityEngine.Object.Instantiate(UnityEngine.GameObject original)
   at ColossalFramework.UI.UIDynamicPanels.Init(ColossalFramework.UI.UIView view)
   at ColossalFramework.UI.UIView.Awake()

[StorageManager.Load] AutoRepair.Options.xml
It looks like there's something wrong with your game install; try common fixes:
 https://steamcommunity.com/sharedfiles/filedetails/?id=467110757 

System.TypeLoadException: Could not load type 'System.Xml.Serialization.XmlRootAttribute' from assembly 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  at AutoRepair.Util.StorageManager`1[AutoRepair.Options].Load () [0x00000] in <filename unknown>:0 
  at AutoRepair.Options.get_Instance () [0x00000] in <filename unknown>:0 
  at AutoRepair.SettingsUI.Render (UIHelperBase helper, System.String scene) [0x00000] in <filename unknown>:0 
  at AutoRepair.UserMod.OnSettingsUI (UIHelperBase helper) [0x00000] in <filename unknown>:0 
   at AutoRepair.Util.Log.LogToFile(System.String message, LogLevel level, Boolean copyToGameLog)
   at AutoRepair.Util.Log.Error(System.String message, Boolean copyToGameLog)
   at AutoRepair.UserMod.OnSettingsUI(UIHelperBase helper)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at OptionsMainPanel.AddUserMods()
   at OptionsMainPanel.CreateCategories()
   at OptionsMainPanel.RefreshPlugins()
   at ColossalFramework.Plugins.PluginManager.TriggerEventPluginsStateChanged()
   at ColossalFramework.Plugins.PluginManager+PluginInfo.set_isEnabled(Boolean value)
   at EntryData.SetActive(Boolean active)
   at PackageEntry.OnCheckedChanged(ColossalFramework.UI.UIComponent c, Boolean check)
   at ColossalFramework.UI.UICheckBox.OnCheckChanged()
   at ColossalFramework.UI.UICheckBox.set_isChecked(Boolean value)
   at ColossalFramework.UI.UICheckBox.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIInput+MouseHandler.ProcessInput(IInputTranslator translator, Ray ray, ColossalFramework.UI.UIComponent component, Boolean retainFocusSetting)
   at ColossalFramework.UI.UIInput.ProcessMouseInput()
   at ColossalFramework.UI.UIInput.Update()

[StorageManager.Load] AutoRepair.Options.xml
It looks like there's something wrong with your game install; try common fixes:
 https://steamcommunity.com/sharedfiles/filedetails/?id=467110757 

System.TypeLoadException: Could not load type 'System.Xml.Serialization.XmlRootAttribute' from assembly 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  at AutoRepair.Util.StorageManager`1[AutoRepair.Options].Load () [0x00000] in <filename unknown>:0 
  at AutoRepair.Options.get_Instance () [0x00000] in <filename unknown>:0 
  at AutoRepair.SettingsUI.Render (UIHelperBase helper, System.String scene) [0x00000] in <filename unknown>:0 
  at AutoRepair.UserMod.OnSettingsUI (UIHelperBase helper) [0x00000] in <filename unknown>:0 
   at AutoRepair.Util.Log.LogToFile(System.String message, LogLevel level, Boolean copyToGameLog)
   at AutoRepair.Util.Log.Error(System.String message, Boolean copyToGameLog)
   at AutoRepair.UserMod.OnSettingsUI(UIHelperBase helper)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at OptionsMainPanel.AddUserMods()
   at OptionsMainPanel.CreateCategories()
   at OptionsMainPanel.RefreshPlugins()
   at ColossalFramework.Plugins.PluginManager.TriggerEventPluginsStateChanged()
   at ColossalFramework.Plugins.PluginManager+PluginInfo.set_isEnabled(Boolean value)
   at EntryData.SetActive(Boolean active)
   at PackageEntry.OnCheckedChanged(ColossalFramework.UI.UIComponent c, Boolean check)
   at ColossalFramework.UI.UICheckBox.OnCheckChanged()
   at ColossalFramework.UI.UICheckBox.set_isChecked(Boolean value)
   at ColossalFramework.UI.UICheckBox.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIInput+MouseHandler.ProcessInput(IInputTranslator translator, Ray ray, ColossalFramework.UI.UIComponent component, Boolean retainFocusSetting)
   at ColossalFramework.UI.UIInput.ProcessMouseInput()
   at ColossalFramework.UI.UIInput.Update()

**Comment by aubergine10** [comment]
Please do the following:

1. Unsubscribe AutoRepair mod
2. Load game to main menu
3. Drag and drop your `output_log.txt` (or `Player.log` if on Mac/Linux) to to comment box below, wait for upload then click "Comment" - I'll be able to get list of mods, etc., from that and hopefully work out what the problem is.

**Comment by szentigrad3** [comment]
[output_log.txt](https://github.com/CitiesSkylinesMods/AutoRepair/files/4605556/output_log.txt)

**Comment by aubergine10** [comment]
Looks like it's CSM (multiplayer?) mod that's causing the problems...

```
Loading C:\Users\nofuk\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\CSM\0Harmony.dll  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Non platform assembly: data-000000001F66E050 (this message is harmless)
Fallback handler could not load library D:/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/data-000000001F66E050.dll
Assembly 0Harmony, Version=2.0.0.8, Culture=neutral, PublicKeyToken=null loaded.  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading C:\Users\nofuk\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\CSM\NLog.dll  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Non platform assembly: data-000000001F721820 (this message is harmless)
Fallback handler could not load library D:/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/data-000000001F721820.dll
Assembly NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c loaded.  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <filename unknown>:0 
  at ColossalFramework.Plugins.PluginManager+PluginInfo.AddAssembly (System.Reflection.Assembly asm) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
ColossalFramework.Plugins.PluginInfo:AddAssembly(Assembly)
ColossalFramework.Plugins.PluginManager:LoadDependenciesRecursive(Assembly, Dictionary`2, Dictionary`2, List`1)
ColossalFramework.Plugins.PluginManager:LoadDependenciesRecursive(Assembly, Dictionary`2, Dictionary`2, List`1)
ColossalFramework.Plugins.PluginManager:LoadDependencies(Dictionary`2, Dictionary`2)
ColossalFramework.Plugins.PluginManager:LoadAssemblies(Dictionary`2)
ColossalFramework.Plugins.PluginManager:LoadPlugins()
Starter:Awake()
 
(Filename:  Line: -1)

Loading C:\Users\nofuk\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\CSM\LiteNetLib.dll  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Non platform assembly: data-000000001F85D080 (this message is harmless)
Fallback handler could not load library D:/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/data-000000001F85D080.dll
Assembly LiteNetLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null loaded.  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading C:\Users\nofuk\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\CSM\System.Threading.dll  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Non platform assembly: data-000000001F874090 (this message is harmless)
Fallback handler could not load library D:/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/data-000000001F874090.dll
Assembly System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35 loaded.  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading C:\Users\nofuk\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\CSM\Open.Nat.dll  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Non platform assembly: data-000000001F8F80F0 (this message is harmless)
Fallback handler could not load library D:/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/data-000000001F8F80F0.dll
Assembly Open.Nat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f22a6a4582336c76 loaded.  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading C:\Users\nofuk\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\CSM\protobuf-net.dll  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Non platform assembly: data-000000001F907900 (this message is harmless)
Fallback handler could not load library D:/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/data-000000001F907900.dll
Assembly protobuf-net, Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67 loaded.  [Mods - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <filename unknown>:0 
  at ColossalFramework.Plugins.PluginManager+PluginInfo.AddAssembly (System.Reflection.Assembly asm) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
ColossalFramework.Plugins.PluginInfo:AddAssembly(Assembly)
ColossalFramework.Plugins.PluginManager:LoadDependenciesRecursive(Assembly, Dictionary`2, Dictionary`2, List`1)
ColossalFramework.Plugins.PluginManager:LoadDependenciesRecursive(Assembly, Dictionary`2, Dictionary`2, List`1)
ColossalFramework.Plugins.PluginManager:LoadDependencies(Dictionary`2, Dictionary`2)
ColossalFramework.Plugins.PluginManager:LoadAssemblies(Dictionary`2)
ColossalFramework.Plugins.PluginManager:LoadPlugins()
Starter:Awake()
```

**Comment by szentigrad3** [comment]
https://github.com/DominicMaas/Tango
